Test multiple package support of apt in CI

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -40,6 +40,11 @@ jobs:
         docker build -t fedora38 -f images/fedora38.Dockerfile scripts/
         docker run --name fedora38-test --network host fedora38 || exit 1
 
+    - name: Build and run Ubuntu 23.04 container for checking multiple package support
+      run: |
+        docker build -t ubuntu23.04-multi -f images/ubuntu23.04-multi-package.Dockerfile scripts/
+        docker run --name ubuntu23.04-multitest --network host ubuntu23.04-multi || exit 1
+
     - name: Check client containers' statuses
       run: |
         if [ "$(docker inspect -f '{{.State.ExitCode}}' ubuntu23.04-test)" -ne 0 ]; then
@@ -52,6 +57,11 @@ jobs:
           exit 1
         fi
 
+        if [ "$(docker inspect -f '{{.State.ExitCode}}' ubuntu23.04-multitest)" -ne 0 ]; then
+          echo "Test on Ubuntu 23.04 for multiple package support failed"
+          exit 1
+        fi
+
     - name: Check server logs
       run: |
         docker logs server-container
@@ -61,3 +71,4 @@ jobs:
         docker rm -f server-container
         docker rm -f ubuntu23.04-test
         docker rm -f fedora38-test
+        docker rm -f ubuntu23.04-multitest
